// Generated by CoffeeScript 1.3.3
(function() {
  var Icon, UIComponent, icon,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  UIComponent = (function() {

    function UIComponent() {}

    UIComponent.propterties = function(properties) {
      return Object.defineProperties(this.prototype, properties);
    };

    UIComponent.editable = function(constructor) {
      var container;
      container = html('container');
      container.id = this.name;
      return this.prototype.edit = constructor(container);
    };

    return UIComponent;

  })();

  Icon = (function(_super) {

    __extends(Icon, _super);

    function Icon(label, action) {
      this.ui = {
        icon: html('icon')
      };
      this.label = label;
      this.action = action;
      this.ui.icon.oncontextmenu = function(event) {
        alert('ok');
        event.preventDefault();
        event.stopPropagation();
        return false;
      };
    }

    Icon.properties({
      label: {
        get: function() {
          return this.ui.icon.innerHTML;
        },
        set: function(text) {
          return this.ui.icon.innerHTML = text;
        }
      },
      action: {
        get: function() {
          return this.ui.icon.onclick;
        },
        set: function(action) {
          return this.ui.icon.onclick = action;
        }
      }
    });

    Icon.editable(function(container) {
      var action, label;
      label = ui.label('label');
      action = ui.script('action');
      container.appendChild(label);
      return container.appendChild(action);
    });

    (function(icon) {
      label.innerHTML = this.label || '';
      action.value = this.action || '';
      return container;
    });

    return Icon;

  })(UIComponent);

  icon = new Icon('test', (function() {
    return log("You clicked me!");
  }));

  $('#toolbar').appendChild(icon.ui.icon);

}).call(this);
