// Generated by CoffeeScript 1.3.3

module.exports = function(application) {
  application.addProject({
    name: 'client',
    path: 'client'
  });
  application.addProject({
    name: 'server',
    path: 'server'
  });
  application.addProject({
    name: 'dungeoncraft',
    path: '/Users/Games/Documents/GitHub/dungeoncraft'
  });
  return application.sitepaths = {
    'dungeoncraft': '/Users/Games/Documents/GitHub/dungeoncraft/lib/client'
  };
};
