coffee = require 'coffee-script'
fs = require 'fs'

option '-f', '--files [FILES*]', 'input files'

task 'onwrite', 'post-write actions', (options)->
	for filename in options.files
		console.log "#{filename}:"
		if filename.match /^[.].+[.]coffee$/
			try
				coffeescript = fs.readFileSync filename, encoding:'utf8'
				javascript = coffee.compile coffeescript, bare:true
				fs.writeFileSync "#{filename}.js", javascript, encoding:'utf8'
				console.log "compiled javascript to #{filename}.js"
			catch error
				console.error error
		else
			console.log "wrote file to #{filename}"